version: 0.2

phases:
  install:
    commands:
      - echo "Skipping runtime install, using existing environment"
  build:
    commands:
      - echo "Build phase - no build needed for PHP"
  post_build:
    commands:
      - echo "Build complete"

artifacts:
  files:
    - '**/*'

