version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "Nothing to install"
  build:
    commands:
      - echo "Nothing to build"
artifacts:
  files:
    - '**/*'

